services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pulperia
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-admin123}
    ports:
      - "3307:3306" # host 3307 -> contenedor 3306 (no choca con tu MySQL de Windows)
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init_db.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${DB_PASSWORD:-admin123} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD:-admin123}
      DB_NAME: pulperia
      SECRET_KEY: ${SECRET_KEY:-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    volumes:
      - ./backend:/app/backend   # hot-reload correcto (mantiene la carpeta 'backend')
    ports:
      - "8000:8000"
    command: ["uvicorn","backend.main:app","--host","0.0.0.0","--port","8000","--reload"]

volumes:
  mysql_data:
